(CONT-200) Fix require relative paths
Prior to this commit using stdlib/to_toml function in a
separate environment outside of production will result
in the following error if the latest version doesn't
also live in production:

```
Error: Could not retrieve catalog from remote server:
Error 500 on SERVER: Internal Server Error:
org.jruby.exceptions.LoadError: (LoadError)
no such file to load -- puppet_x/stdlib
```

This commit fixes the issue by updating code to use the correct paths
for require_relative.